name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: seq-rs/actions/rust-cache@v1
      - run: cargo check --workspace
      - run: cargo test --workspace
      - run: cargo test --workspace --all-features
      - run: cargo clippy --workspace --all-features -- -D warnings
