name: Publish to crates.io

on:
  push:
    tags: ["v*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release  # Optional: for enhanced security
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - uses: seq-rs/actions/rust-cache@v1

      - run: cargo test --workspace


      - run: cargo publish -p yaml0
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
